name = "TMAGE"
uuid = "d5373340-7f11-4df9-a85d-66f3c9444a86"
authors = ["Camilo De La Torre"]
version = "1.0.0-DEV"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
GraphViz = "f526b714-d49f-11e8-06ff-31ed36ee7ee0"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ThreadSafeDicts = "4239201d-c60e-5e0a-9702-85d713665ba7"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UTCGP = "956831e1-0a7a-492a-ae16-058c6128a9f2"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
DataStructures = ">=0.18.22"
Debugger = "0.7.11"
GraphViz = ">=0.2.0"
Infiltrator = "1.9.4"
IterTools = "1.10.0"
LRUCache = ">=1.6.2"
Random = "1.11.0"
Revise = "3.7.5"
Statistics = ">=1.11.1"
StatsBase = ">=0.33.21"
Test = ">=1.11.0"
ThreadSafeDicts = ">=0.1.6"
TimerOutputs = "0.5.29"
UnicodePlots = "3.6.0"
